### ISSUE TITLE
Scatter plots do not show face colour

### ISSUE THREAD

**Issue by fdeugenio** [AstroJacobLi/smplotlib#1]
Hi, great library! I was wondering whether you can create scatter plots with the symbols colour coded, e.g.:
```
import numpy as np
v = np.arange(10)
plt.scatter(v, v, c=v)
```
With `smplotlib`, all symbols are empty white circles, but without `smplotlib`, the symbols are coloured. Perhaps this is a deliberate style choice, but just wanted to report in case it's not!

**Comment by AstroJacobLi** [comment]
Hi there! Thanks for rasing this issue. I tested it using the latest version of `smplotlib` on pip (https://pypi.org/project/smplotlib/), and I got the following figure without the problem that you reported:
![image](https://github.com/AstroJacobLi/smplotlib/assets/29670581/c5cc1656-4fe9-4377-a053-c207c503b268)

Maybe can you try to upgrade the package by `pip install smplotlib -U`?

**Comment by fdeugenio** [comment]
I tried that but get the same results, differently from what you display. I have this setup
matplotlib 3.7.1
smplotlib 0.0.8
Python 3.10.9

**Comment by AstroJacobLi** [comment]
Okay I was using a much older version of matplotlib. And I can reproduce your issue when using matplotlib 3.7.1. I'll try to fix it later. Thanks for raising the issue!

**Comment by AstroJacobLi** [comment]
Hi @fdeugenio! I think I've fixed the problem. The figure below is generated using the latest `smplotlib==0.0.9` and the following code:
```python
import numpy as np
v = np.arange(10)
plt.scatter(v, v, c=v)
plt.text(5.5, 2, r'Normal Text', fontsize=18)
plt.text(5.5, 2.5, r'$\mathbf{mathbf}$', fontsize=18)
plt.text(5.5, 3, r'$\mathit{mathit}$', fontsize=18)
plt.text(5.5, 3.5, r'$\mathsf{mathsf}$', fontsize=18)
plt.text(5.5, 4, r'$\mathtt{mathtt}$', fontsize=18)
```
![image](https://github.com/AstroJacobLi/smplotlib/assets/29670581/ab6e9c94-b027-42d9-bc01-59449b66ffeb)

This demonstrates the different types of fonts in the Hershey font family. If you don't like the black edge around the data points, you can turn it off by `smplotlib.set_style(edgecolor='face')`. The default colormap is jet, to mimic those shining old figures, you know...

**Comment by fdeugenio** [comment]
Awesome, thank you! I also learned about `fillstyle` looking at your commit
